version: '3.8'

services:
  web:
    build: .
    entrypoint: /app/entrypoint.sh
    working_dir: /app/GSsite
    volumes:
      - .:/app
      - static_volume:/app/GSsite/staticfiles
      - media_volume:/app/GSsite/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery
      - celery-beat

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    working_dir: /app/GSsite
    command: celery -A GSsite worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    working_dir: /app/GSsite
    command: celery -A GSsite beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  nginx:
    image: nginx:1.25
    volumes:
      - static_volume:/app/GSsite/staticfiles
      - media_volume:/app/GSsite/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs:/app/logs
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume: 