# Generated by Django 5.2.1 on 2025-06-12 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_monitor", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                ("emergency_alerts", models.BooleanField(default=True)),
                ("heart_rate_min", models.IntegerField(default=60)),
                ("heart_rate_max", models.IntegerField(default=100)),
                ("systolic_bp_min", models.IntegerField(default=90)),
                ("systolic_bp_max", models.IntegerField(default=140)),
                ("diastolic_bp_min", models.IntegerField(default=60)),
                ("diastolic_bp_max", models.IntegerField(default=90)),
                (
                    "body_temp_min",
                    models.DecimalField(decimal_places=1, default=36.5, max_digits=4),
                ),
                (
                    "body_temp_max",
                    models.DecimalField(decimal_places=1, default=37.5, max_digits=4),
                ),
                ("share_with_staff", models.BooleanField(default=True)),
                ("share_with_family", models.BooleanField(default=True)),
                ("contribute_research_data", models.BooleanField(default=False)),
                ("data_retention_period", models.IntegerField(default=12)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
