# Generated by Django 5.2.1 on 2025-06-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "health_monitor",
            "0002_alter_userprofile_gender_alter_userprofile_id_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="device_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
